name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        export TAG=$(date +%s)
        docker build . --file Dockerfile --tag stocky:$TAG
        docker push ghcr.io/p16n/stocky:$TAG
